export const BUTTON = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  SUBMIT: 'Submit',
  SAVE: 'Save',
  SAVE_RUN: 'Save & Run',
  SAVE_RUN_SCENARIO: 'Save & Run Scenario',
  FINISH: 'Finish',
  YES: 'Yes',
  NO: 'No',
  CANCEL: 'Cancel',
  NEXT: 'Next Step',
  PREVIOUS: 'Previous',
  GENERATE: 'Create Scenario',
  COMPARE: 'Compare Scenarios',
  DELETE_SCENARIOS: 'Delete Scenarios',
  COMPARE_RESULTS: 'Compare results',
  EXPORT_PDF: 'Export as PDF',
  DUPLICATE: 'Duplicate',
  VIEW: 'View',
  EDIT: 'Edit',
  DELETE: 'Delete',
  DISABLE: 'Disable',
  ENABLE: 'ENABLE',
  SAVETOCSV: 'Save to CSV',
  DISABLED: 'This function is disabled for the moment.',
  USER: 'Make it Admin',
  ADMIN: 'Make it User',
};
